name: Linux GUI Build
run-name: Linux GUI Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: linux-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
      
      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --windowed  transcription.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: |
            dist/*.exe
          include-hidden-files: true
