name: MacOS GUI Build
run-name: MacOS GUI Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
      
      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller -F transcription.py

      - name: List Dist
        run: ls -l ./dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MacOS Build
          path: |
            dist/*.bin
            dist/*.app/**/*
          include-hidden-files: true
