name: macos tkinter minimal

on:
    workflow_dispatch:

jobs:
  minimal:
    runs-on: macos-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
      - name: Install Depencencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt

      - name: import tkinter
        run: |
          ls -l /Library/Frameworks/Python.framework/Versions/
          # python -c "import tkinter; print(f'Tkinter imported successfully. Version: {tkinter.TkVersion}')"

