name: macos tkinter minimal

on:
    workflow_dispatch:

jobs:
  minimal:
    runs-on: macos-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: listing libraries
        run: |
          ls -la /Library/Frameworks/Python.framework/Versions/Current/Frameworks/Tcl.framework/Tcl/
          # python -c "import tkinter; print(f'Tkinter imported successfully. Version: {tkinter.TkVersion}')"

